image: jethubjhaos/{machine}-homeassistant
shadow_repository: ghcr.io/jethubjhaos
build_from:
  aarch64: "ghcr.io/jethubjhaos/aarch64-homeassistant:"
  armv7: "ghcr.io/jethubjhaos/armv7-homeassistant:"
  armhf: "ghcr.io/jethubjhaos/armhf-homeassistant:"
  amd64: "ghcr.io/jethubjhaos/amd64-homeassistant:"
  i386: "ghcr.io/jethubjhaos/i386-homeassistant:"
codenotary:
  signer: vb@jethome.ru
  base_image: vb@jethome.ru
labels:
  io.hass.type: core
  org.opencontainers.image.source: https://github.com/jethubjhaos/core
